# publication settings

lang: en 

toc-title: "Contents" 
reference-section-title: "References" 
link-citations: true

# website settings

title-card-bg-color: "#3D2F5B"

cover: true

format: # full-text download options
  - label: Online
    link: textbook.html
  - label: PDF
    link: textbook.pdf
  - label: EPUB
    link: textbook.epub
  - label: DOCX
    link: textbook.docx
  - label: LATEX
    link: textbook.tex
  - label: GitHub
    link: https://github.com/nulib-oer/lantern

# pandoc-crossref option
linkReferences: true

# print settings

paper:
  # available units: in, cm, or mm
  # default creates A4 page size, > 150 pages long
  width: 8.27in
  height: 11.69in
  gutter: 1in
  margin:
    top: 1in
    bottom: 1in
    left: 1in
    right: 1in

# ConTeXt settings

papersize: a4 # a4, a5, letter
fontsize: 12pt

# these fonts are available with ConTeXt: https://wiki.contextgarden.net/ConTeXt_distribution%27s_Fonts
mainfont: DejaVu serif
sansfont: DejaVu sans
monofont: DejaVu sansmono
mathfont: Latin Modern Math

linkcolor: Sapphire # color options: https://wiki.contextgarden.net/Color#Crayola_crayon_colors
linkstyle: bold # normal, bold, slanted, boldslanted, type, cap, small

